### ISSUE TITLE
Download File in Client

### ISSUE THREAD

**Issue by ralphievolt** [tarique93102/gridfs-file-storage#3]
I've been trying to follow your tutorial and so far I'm stuck on how to download the file in the client

 ```
 imageRouter.route("/file/:filename").get((req, res, next) => {
    gfs.find({ filename: req.params.filename }).toArray((err, files) => {
      if (!files[0] || files.length === 0) {
        return res.status(200).json({
          success: false,
          message: "No files available",
        });
      }
      console.log("getter", files[0]);
      res.status(200).json({
        success: true,
        file: files[0],
      });
    });
  });
```
I am using React and already spent two days trying to download the file in the client. I know the the uploading is right since I can see the file and download the file using sa NoSQLBooster MongoDB Client

My use case is when i have the list the user can have the option to download the file..

Thanks

**Comment by ralphievolt** [comment]
I can download the file by the way but when opening the .docx file , it's error

**Comment by tejazz** [comment]
Can you share the snippet of the download code on the react side?

**Comment by ralphievolt** [comment]
here's the code

```
  _getFile = async () => {
    const downloadFilename = "7e302e69b3721d974bcbe75e35452b65.pdf";

    axios({
      method: "GET",
      url: " http://localhost:9890/file/" + downloadFilename,
      responseType: "blob",
    })
      .then((response) => {
        FileSaver.saveAs(response.data, "test.pdf");
        console.log(response);
      })
      .then(() => {
        console.log("Completed");
      });

  };
```

**Comment by tejazz** [comment]
The reason you are not able to get the file is that you have to stream the file data back to the client. I have not tested it yet. But I believe that using

```
gfs.openDownloadStreamByName(req.params.filename).pipe(res);
```

instead of 

```
    res.status(200).json({
       success: true,
       file: files[0],
     });
```

should do the trick. Let me know if it still fails. I will try to replicate the use case.

**Comment by ralphievolt** [comment]
Great!!! It's working now. Thank you very much!
